
# Query modes

ASYNC_QUERY = 'broker'
TALARIA_INDEXER = 'indexer'
TALARIA_SERVER = 'server'

ASYNC_INITIALIZED = 'INITIALIZED'
ASYNC_RUNNING = 'RUNNING'
ASYNC_COMPLETE = 'COMPLETE'
ASYNC_FAILED = 'FAILED'

SQL_TASK_RUNNING = 'RUNNING'
SQL_TASK_FAILED = 'FAILED'

MSQE_TASKS_KEY = 'msqNumTasks'

# Talaria task filters
ALL_LEADERS = 'ALL'
WAITING_LEADERS = 'WAITING'
RUNNING_LEADRERS = 'RUNNING'
COMPLETED_LEADERS = 'COMPLETED'
FAILED_LEADERS = 'FAILED'

# Async fields
ASYNC_ID_KEY = 'asyncResultId'
ASYNC_STATE_KEY = 'state'
ASYNC_RESULT_FORMAT_KEY = 'resultFormat'
ASYNC_ENGINE_KEY = 'engine'

BROKER_ENGINE = 'Broker'
ASYNC_BROKER_ENGINE = 'Async'
TASK_ENGINE = 'Task'
