
# Query modes

ASYNC_QUERY = 'broker'
TALARIA_INDEXER = 'indexer'
TALARIA_SERVER = 'server'

ASYNC_INITIALIZED = 'INITIALIZED'
ASYNC_RUNNING = 'RUNNING'
ASYNC_COMPLETE = 'COMPLETE'
ASYNC_FAILED = 'FAILED'

TALARIA_KEY = 'talaria'
